services:
  backend:
    build: ./backend
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=mysql+pymysql://user:pass@mysql-db/dbname
      - MONGODB_URL=mongodb://mongo-db:27017/dbname
      - NEO4J_URL=bolt://neo4j-db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j_pass
    depends_on:
      - mysql-db
      - mongo-db
      - neo4j-db

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend

  mysql-db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"

  mongo-db:
    image: mongo:7.0
    restart: always
    ports:
      - "27017:27017"

  neo4j-db:
    image: neo4j:5.22
    restart: always
    environment:
      NEO4J_AUTH: neo4j/neo4j_pass
    ports:
      - "7474:7474"
      - "7687:7687"
